### ISSUE TITLE
unable to make web-service call from the broadcast class.

### ISSUE THREAD

**Issue by aurk** [RefineriaWeb/base_app_android#3]
I am unable to make web-service call from the broadcast class.

I'm using this project as a base project and now I am facing issue in making network call from the broadcast class. It is because presenter is not available on the broadcast. Is there any way to make network-call from it.

My task is to make network call after every 2 hours. So this should be done via broadcast that's why I think it is necessary to do this task using broadcast. Please help me to implement this task.

**Comment by VictorAlbertos** [comment]
Hi. 

You need to register in your application component your broadcast class. And inject in it every dependency as a field injection, in a similar way that it is done when using activities or fragments.

**Comment by aurk** [comment]
Sorry, I'm really unable to understand your answer.

> You need to register in your application component your broadcast class.
> Done. Got it.
> 
> And inject in it every dependency as a field injection, in a similar way that it is done when using activities or fragments. 
> Unable to understand this point.

`public class TopQuizBroadCast extends BroadcastReceiver{
    @Override
    public void onReceive(Context context, Intent intent) {
        try {
            DBManager dbManager = DBManager.getInstances(context);
            MainActivity.presenter.getTopQuizes(dbManager.getAuthKey(), "all_time");
        }catch (Exception e){
            e.printStackTrace();
        }
    }
}`
Right now, I have made presenter static but it should not be static. Do you mean, I have to inject presenter at this broadcast class and implement Subscription method here ?
